name: dart_levenshtein 
description: Levenshtein distance implementation in Dart. The levenshtein distance can be invoked as a function or as a String extension.
version: 1.0.1
homepage: https://github.com/Makepad-fr/dart_levenshtein
issue_tracker: https://github.com/Makepad-fr/dart_levenshtein/issues
repository: https://github.com/Makepad-fr/dart_levenshtein

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
